import turtle
import time
import random
bob=turtle.Turtle()
screen = turtle.Screen()
screen.title('NIGHTMARE')
clownlist=['yellow' , 'gold' , 'orange' , 'red' , 'maroon' , 'violet' , 'magenta' , 'purple' , 'navy' , 'blue' , 'skyblue' , 'cyan' , 'turquoise' , 'lightgreen' , 'green' , 'darkgreen' , 'chocolate' , 'brown' , 'black' , 'gray' , 'white']
bob.speed('fastest')
bob.hideturtle()
screen.bgcolor('black')
bob.width(2)
#screen.setup(width=1000, height=1200)
zach = turtle.Turtle()
zach.hideturtle()
zach.speed('fastest')
zach.width(6)
zach.color('white')
zach.right(90)
zach.up()
zach.forward(50)
zach.down()
zach.write('SEIZURE WARNING!', font=10)
time.sleep(3)
fred=turtle.Turtle()
fred.speed('fastest')
fred.hideturtle()
fred.up()
fred.left(90)
fred.forward(150)
fred.down()
fred.right(90)
fred.width(2)
turtle.tracer(10000)
for t in range(120):
    clown = random.choice(clownlist)
    bob.color(clown)
    bob.circle(50)
    fred.color(clown)
    fred.circle(50)
    screen.bgcolor(clown)
    bob.forward(2.5)
    fred.forward(5)
    bob.color(clown)
    fred.color(clown)
    bob.circle(50)
    fred.circle(50)
    screen.bgcolor(clown)
    bob.right(6)
    fred.right(3)
    bob.forward(2.75)
    fred.forward(5.5)
    bob.color(clown)
    fred.color(clown)
    bob.circle(50)
    fred.circle(50)
    screen.bgcolor(clown)
    screen.bgcolor('pink')
brick=150
zach.right(90)
zach.up()
zach.forward(150)
zach.left(90)
zach.down()
zach.circle(brick)

for t in range(20):
    zach.up()
    zach.right(90)
    zach.forward(2.5)
    zach.down()
    zach.left(90)
    brick=brick+2.5
    zach.circle(brick)

titus=turtle.Turtle()
titus.hideturtle()
titus.color(clown)
titus.right(90)
titus.up()
titus.forward(50)
titus.down()
titus.dot(100)

hello=5
ark=turtle.Turtle()
ark.width(2)
ark.speed('fastest')
ark.color(clown)
ark.hideturtle()
ark.right(90)
ark.up()
ark.forward(50)
ark.right(90)
ark.forward(5)
ark.left(90)
ark.down()
ark.circle(hello)
for x in range(59):
    hello=hello+5
    ark.up()
    ark.right(90)
    ark.forward(5)
    ark.down()
    ark.left(90)
    ark.circle(hello)
fred.left(90)
fred.up()
fred.forward(100)
fred.down()
fred.right(90)
fred.forward(300)



    
   
    
